INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰1', '홍길동1', 'NORMAL', 100, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰2', '홍길동2', 'NORMAL', 1000, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰3', '홍길동3', 'NORMAL', 500, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰4', '홍길동4', 'ADULT', 1500, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰5', '홍길동5', 'ADULT', 5000, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
INSERT INTO WEBTOON_INFO (NAME, AUTHOR, RATING_TYPE, COIN, OPEN_DATE, REG_DATE, UPT_DATE)
VALUES ('웹툰6', '홍길동6', 'ADULT', 10000, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));